// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.BusinessUnit;

privileged aspect BusinessUnit_Roo_JavaBean {
    
    public String BusinessUnit.getName() {
        return this.name;
    }
    
    public void BusinessUnit.setName(String name) {
        this.name = name;
    }
    
}
