// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.ContractType;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContractType_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ContractType.entityManager;
    
    public static final EntityManager ContractType.entityManager() {
        EntityManager em = new ContractType().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ContractType.countContractTypes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ContractType o", Long.class).getSingleResult();
    }
    
    public static List<ContractType> ContractType.findAllContractTypes() {
        return entityManager().createQuery("SELECT o FROM ContractType o", ContractType.class).getResultList();
    }
    
    public static ContractType ContractType.findContractType(Long id) {
        if (id == null) return null;
        return entityManager().find(ContractType.class, id);
    }
    
    public static List<ContractType> ContractType.findContractTypeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ContractType o", ContractType.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ContractType.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ContractType.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ContractType attached = ContractType.findContractType(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ContractType.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ContractType.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ContractType ContractType.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ContractType merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
