// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.OpCenter;

privileged aspect OpCenter_Roo_JavaBean {
    
    public String OpCenter.getName() {
        return this.name;
    }
    
    public void OpCenter.setName(String name) {
        this.name = name;
    }
    
}
