// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.BusinessUnit;
import com.saic.tmr.domain.BusinessUnitDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BusinessUnitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BusinessUnitDataOnDemand: @Component;
    
    private Random BusinessUnitDataOnDemand.rnd = new SecureRandom();
    
    private List<BusinessUnit> BusinessUnitDataOnDemand.data;
    
    public BusinessUnit BusinessUnitDataOnDemand.getNewTransientBusinessUnit(int index) {
        BusinessUnit obj = new BusinessUnit();
        setName(obj, index);
        return obj;
    }
    
    public void BusinessUnitDataOnDemand.setName(BusinessUnit obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public BusinessUnit BusinessUnitDataOnDemand.getSpecificBusinessUnit(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BusinessUnit obj = data.get(index);
        Long id = obj.getId();
        return BusinessUnit.findBusinessUnit(id);
    }
    
    public BusinessUnit BusinessUnitDataOnDemand.getRandomBusinessUnit() {
        init();
        BusinessUnit obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return BusinessUnit.findBusinessUnit(id);
    }
    
    public boolean BusinessUnitDataOnDemand.modifyBusinessUnit(BusinessUnit obj) {
        return false;
    }
    
    public void BusinessUnitDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BusinessUnit.findBusinessUnitEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BusinessUnit' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BusinessUnit>();
        for (int i = 0; i < 10; i++) {
            BusinessUnit obj = getNewTransientBusinessUnit(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
