// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.BusinessUnit;
import com.saic.tmr.domain.BusinessUnitDataOnDemand;
import com.saic.tmr.domain.BusinessUnitIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BusinessUnitIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BusinessUnitIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BusinessUnitIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BusinessUnitIntegrationTest: @Transactional;
    
    @Autowired
    private BusinessUnitDataOnDemand BusinessUnitIntegrationTest.dod;
    
    @Test
    public void BusinessUnitIntegrationTest.testCountBusinessUnits() {
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", dod.getRandomBusinessUnit());
        long count = BusinessUnit.countBusinessUnits();
        Assert.assertTrue("Counter for 'BusinessUnit' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testFindBusinessUnit() {
        BusinessUnit obj = dod.getRandomBusinessUnit();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to provide an identifier", id);
        obj = BusinessUnit.findBusinessUnit(id);
        Assert.assertNotNull("Find method for 'BusinessUnit' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BusinessUnit' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testFindAllBusinessUnits() {
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", dod.getRandomBusinessUnit());
        long count = BusinessUnit.countBusinessUnits();
        Assert.assertTrue("Too expensive to perform a find all test for 'BusinessUnit', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BusinessUnit> result = BusinessUnit.findAllBusinessUnits();
        Assert.assertNotNull("Find all method for 'BusinessUnit' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BusinessUnit' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testFindBusinessUnitEntries() {
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", dod.getRandomBusinessUnit());
        long count = BusinessUnit.countBusinessUnits();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BusinessUnit> result = BusinessUnit.findBusinessUnitEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BusinessUnit' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BusinessUnit' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testFlush() {
        BusinessUnit obj = dod.getRandomBusinessUnit();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to provide an identifier", id);
        obj = BusinessUnit.findBusinessUnit(id);
        Assert.assertNotNull("Find method for 'BusinessUnit' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBusinessUnit(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BusinessUnit' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testMergeUpdate() {
        BusinessUnit obj = dod.getRandomBusinessUnit();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to provide an identifier", id);
        obj = BusinessUnit.findBusinessUnit(id);
        boolean modified =  dod.modifyBusinessUnit(obj);
        Integer currentVersion = obj.getVersion();
        BusinessUnit merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BusinessUnit' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", dod.getRandomBusinessUnit());
        BusinessUnit obj = dod.getNewTransientBusinessUnit(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BusinessUnit' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BusinessUnit' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BusinessUnitIntegrationTest.testRemove() {
        BusinessUnit obj = dod.getRandomBusinessUnit();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BusinessUnit' failed to provide an identifier", id);
        obj = BusinessUnit.findBusinessUnit(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BusinessUnit' with identifier '" + id + "'", BusinessUnit.findBusinessUnit(id));
    }
    
}
