// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.Command;
import com.saic.tmr.domain.CommandDataOnDemand;
import com.saic.tmr.domain.CommandIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CommandIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CommandIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CommandIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CommandIntegrationTest: @Transactional;
    
    @Autowired
    private CommandDataOnDemand CommandIntegrationTest.dod;
    
    @Test
    public void CommandIntegrationTest.testCountCommands() {
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", dod.getRandomCommand());
        long count = Command.countCommands();
        Assert.assertTrue("Counter for 'Command' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CommandIntegrationTest.testFindCommand() {
        Command obj = dod.getRandomCommand();
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Command' failed to provide an identifier", id);
        obj = Command.findCommand(id);
        Assert.assertNotNull("Find method for 'Command' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Command' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CommandIntegrationTest.testFindAllCommands() {
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", dod.getRandomCommand());
        long count = Command.countCommands();
        Assert.assertTrue("Too expensive to perform a find all test for 'Command', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Command> result = Command.findAllCommands();
        Assert.assertNotNull("Find all method for 'Command' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Command' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CommandIntegrationTest.testFindCommandEntries() {
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", dod.getRandomCommand());
        long count = Command.countCommands();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Command> result = Command.findCommandEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Command' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Command' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CommandIntegrationTest.testFlush() {
        Command obj = dod.getRandomCommand();
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Command' failed to provide an identifier", id);
        obj = Command.findCommand(id);
        Assert.assertNotNull("Find method for 'Command' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCommand(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Command' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommandIntegrationTest.testMergeUpdate() {
        Command obj = dod.getRandomCommand();
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Command' failed to provide an identifier", id);
        obj = Command.findCommand(id);
        boolean modified =  dod.modifyCommand(obj);
        Integer currentVersion = obj.getVersion();
        Command merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Command' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommandIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", dod.getRandomCommand());
        Command obj = dod.getNewTransientCommand(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Command' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Command' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Command' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CommandIntegrationTest.testRemove() {
        Command obj = dod.getRandomCommand();
        Assert.assertNotNull("Data on demand for 'Command' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Command' failed to provide an identifier", id);
        obj = Command.findCommand(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Command' with identifier '" + id + "'", Command.findCommand(id));
    }
    
}
