// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.Command;
import com.saic.tmr.domain.CommandDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CommandDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CommandDataOnDemand: @Component;
    
    private Random CommandDataOnDemand.rnd = new SecureRandom();
    
    private List<Command> CommandDataOnDemand.data;
    
    public Command CommandDataOnDemand.getNewTransientCommand(int index) {
        Command obj = new Command();
        setName(obj, index);
        return obj;
    }
    
    public void CommandDataOnDemand.setName(Command obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Command CommandDataOnDemand.getSpecificCommand(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Command obj = data.get(index);
        Long id = obj.getId();
        return Command.findCommand(id);
    }
    
    public Command CommandDataOnDemand.getRandomCommand() {
        init();
        Command obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Command.findCommand(id);
    }
    
    public boolean CommandDataOnDemand.modifyCommand(Command obj) {
        return false;
    }
    
    public void CommandDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Command.findCommandEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Command' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Command>();
        for (int i = 0; i < 10; i++) {
            Command obj = getNewTransientCommand(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
