// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.ContractType;
import com.saic.tmr.domain.ContractTypeDataOnDemand;
import com.saic.tmr.domain.ContractTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContractTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContractTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContractTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContractTypeIntegrationTest: @Transactional;
    
    @Autowired
    private ContractTypeDataOnDemand ContractTypeIntegrationTest.dod;
    
    @Test
    public void ContractTypeIntegrationTest.testCountContractTypes() {
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", dod.getRandomContractType());
        long count = ContractType.countContractTypes();
        Assert.assertTrue("Counter for 'ContractType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContractTypeIntegrationTest.testFindContractType() {
        ContractType obj = dod.getRandomContractType();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to provide an identifier", id);
        obj = ContractType.findContractType(id);
        Assert.assertNotNull("Find method for 'ContractType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ContractType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContractTypeIntegrationTest.testFindAllContractTypes() {
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", dod.getRandomContractType());
        long count = ContractType.countContractTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ContractType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ContractType> result = ContractType.findAllContractTypes();
        Assert.assertNotNull("Find all method for 'ContractType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ContractType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContractTypeIntegrationTest.testFindContractTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", dod.getRandomContractType());
        long count = ContractType.countContractTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ContractType> result = ContractType.findContractTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ContractType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ContractType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContractTypeIntegrationTest.testFlush() {
        ContractType obj = dod.getRandomContractType();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to provide an identifier", id);
        obj = ContractType.findContractType(id);
        Assert.assertNotNull("Find method for 'ContractType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContractType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ContractType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContractTypeIntegrationTest.testMergeUpdate() {
        ContractType obj = dod.getRandomContractType();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to provide an identifier", id);
        obj = ContractType.findContractType(id);
        boolean modified =  dod.modifyContractType(obj);
        Integer currentVersion = obj.getVersion();
        ContractType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ContractType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContractTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", dod.getRandomContractType());
        ContractType obj = dod.getNewTransientContractType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ContractType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ContractType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ContractType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContractTypeIntegrationTest.testRemove() {
        ContractType obj = dod.getRandomContractType();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContractType' failed to provide an identifier", id);
        obj = ContractType.findContractType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ContractType' with identifier '" + id + "'", ContractType.findContractType(id));
    }
    
}
