// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.OpCenter;
import com.saic.tmr.domain.OpCenterDataOnDemand;
import com.saic.tmr.domain.OpCenterIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OpCenterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OpCenterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OpCenterIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OpCenterIntegrationTest: @Transactional;
    
    @Autowired
    private OpCenterDataOnDemand OpCenterIntegrationTest.dod;
    
    @Test
    public void OpCenterIntegrationTest.testCountOpCenters() {
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", dod.getRandomOpCenter());
        long count = OpCenter.countOpCenters();
        Assert.assertTrue("Counter for 'OpCenter' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OpCenterIntegrationTest.testFindOpCenter() {
        OpCenter obj = dod.getRandomOpCenter();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to provide an identifier", id);
        obj = OpCenter.findOpCenter(id);
        Assert.assertNotNull("Find method for 'OpCenter' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OpCenter' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OpCenterIntegrationTest.testFindAllOpCenters() {
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", dod.getRandomOpCenter());
        long count = OpCenter.countOpCenters();
        Assert.assertTrue("Too expensive to perform a find all test for 'OpCenter', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OpCenter> result = OpCenter.findAllOpCenters();
        Assert.assertNotNull("Find all method for 'OpCenter' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OpCenter' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OpCenterIntegrationTest.testFindOpCenterEntries() {
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", dod.getRandomOpCenter());
        long count = OpCenter.countOpCenters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OpCenter> result = OpCenter.findOpCenterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OpCenter' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OpCenter' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OpCenterIntegrationTest.testFlush() {
        OpCenter obj = dod.getRandomOpCenter();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to provide an identifier", id);
        obj = OpCenter.findOpCenter(id);
        Assert.assertNotNull("Find method for 'OpCenter' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOpCenter(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'OpCenter' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OpCenterIntegrationTest.testMergeUpdate() {
        OpCenter obj = dod.getRandomOpCenter();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to provide an identifier", id);
        obj = OpCenter.findOpCenter(id);
        boolean modified =  dod.modifyOpCenter(obj);
        Integer currentVersion = obj.getVersion();
        OpCenter merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'OpCenter' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OpCenterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", dod.getRandomOpCenter());
        OpCenter obj = dod.getNewTransientOpCenter(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OpCenter' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'OpCenter' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OpCenterIntegrationTest.testRemove() {
        OpCenter obj = dod.getRandomOpCenter();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OpCenter' failed to provide an identifier", id);
        obj = OpCenter.findOpCenter(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OpCenter' with identifier '" + id + "'", OpCenter.findOpCenter(id));
    }
    
}
