// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.ProcurementType;
import com.saic.tmr.domain.ProcurementTypeDataOnDemand;
import com.saic.tmr.domain.ProcurementTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProcurementTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProcurementTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProcurementTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProcurementTypeIntegrationTest: @Transactional;
    
    @Autowired
    private ProcurementTypeDataOnDemand ProcurementTypeIntegrationTest.dod;
    
    @Test
    public void ProcurementTypeIntegrationTest.testCountProcurementTypes() {
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", dod.getRandomProcurementType());
        long count = ProcurementType.countProcurementTypes();
        Assert.assertTrue("Counter for 'ProcurementType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testFindProcurementType() {
        ProcurementType obj = dod.getRandomProcurementType();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to provide an identifier", id);
        obj = ProcurementType.findProcurementType(id);
        Assert.assertNotNull("Find method for 'ProcurementType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProcurementType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testFindAllProcurementTypes() {
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", dod.getRandomProcurementType());
        long count = ProcurementType.countProcurementTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProcurementType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProcurementType> result = ProcurementType.findAllProcurementTypes();
        Assert.assertNotNull("Find all method for 'ProcurementType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProcurementType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testFindProcurementTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", dod.getRandomProcurementType());
        long count = ProcurementType.countProcurementTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProcurementType> result = ProcurementType.findProcurementTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProcurementType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProcurementType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testFlush() {
        ProcurementType obj = dod.getRandomProcurementType();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to provide an identifier", id);
        obj = ProcurementType.findProcurementType(id);
        Assert.assertNotNull("Find method for 'ProcurementType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProcurementType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProcurementType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testMergeUpdate() {
        ProcurementType obj = dod.getRandomProcurementType();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to provide an identifier", id);
        obj = ProcurementType.findProcurementType(id);
        boolean modified =  dod.modifyProcurementType(obj);
        Integer currentVersion = obj.getVersion();
        ProcurementType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProcurementType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", dod.getRandomProcurementType());
        ProcurementType obj = dod.getNewTransientProcurementType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProcurementType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProcurementType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProcurementTypeIntegrationTest.testRemove() {
        ProcurementType obj = dod.getRandomProcurementType();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProcurementType' failed to provide an identifier", id);
        obj = ProcurementType.findProcurementType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProcurementType' with identifier '" + id + "'", ProcurementType.findProcurementType(id));
    }
    
}
