// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.ProcurementType;
import com.saic.tmr.domain.ProcurementTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProcurementTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProcurementTypeDataOnDemand: @Component;
    
    private Random ProcurementTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ProcurementType> ProcurementTypeDataOnDemand.data;
    
    public ProcurementType ProcurementTypeDataOnDemand.getNewTransientProcurementType(int index) {
        ProcurementType obj = new ProcurementType();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ProcurementTypeDataOnDemand.setCode(ProcurementType obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void ProcurementTypeDataOnDemand.setName(ProcurementType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ProcurementType ProcurementTypeDataOnDemand.getSpecificProcurementType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProcurementType obj = data.get(index);
        Long id = obj.getId();
        return ProcurementType.findProcurementType(id);
    }
    
    public ProcurementType ProcurementTypeDataOnDemand.getRandomProcurementType() {
        init();
        ProcurementType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProcurementType.findProcurementType(id);
    }
    
    public boolean ProcurementTypeDataOnDemand.modifyProcurementType(ProcurementType obj) {
        return false;
    }
    
    public void ProcurementTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProcurementType.findProcurementTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProcurementType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProcurementType>();
        for (int i = 0; i < 10; i++) {
            ProcurementType obj = getNewTransientProcurementType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
