// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.Pursuit;
import com.saic.tmr.domain.PursuitDataOnDemand;
import com.saic.tmr.domain.PursuitIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PursuitIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PursuitIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PursuitIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PursuitIntegrationTest: @Transactional;
    
    @Autowired
    private PursuitDataOnDemand PursuitIntegrationTest.dod;
    
    @Test
    public void PursuitIntegrationTest.testCountPursuits() {
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", dod.getRandomPursuit());
        long count = Pursuit.countPursuits();
        Assert.assertTrue("Counter for 'Pursuit' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PursuitIntegrationTest.testFindPursuit() {
        Pursuit obj = dod.getRandomPursuit();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to provide an identifier", id);
        obj = Pursuit.findPursuit(id);
        Assert.assertNotNull("Find method for 'Pursuit' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pursuit' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PursuitIntegrationTest.testFindAllPursuits() {
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", dod.getRandomPursuit());
        long count = Pursuit.countPursuits();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pursuit', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pursuit> result = Pursuit.findAllPursuits();
        Assert.assertNotNull("Find all method for 'Pursuit' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pursuit' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PursuitIntegrationTest.testFindPursuitEntries() {
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", dod.getRandomPursuit());
        long count = Pursuit.countPursuits();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pursuit> result = Pursuit.findPursuitEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Pursuit' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pursuit' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PursuitIntegrationTest.testFlush() {
        Pursuit obj = dod.getRandomPursuit();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to provide an identifier", id);
        obj = Pursuit.findPursuit(id);
        Assert.assertNotNull("Find method for 'Pursuit' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPursuit(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Pursuit' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PursuitIntegrationTest.testMergeUpdate() {
        Pursuit obj = dod.getRandomPursuit();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to provide an identifier", id);
        obj = Pursuit.findPursuit(id);
        boolean modified =  dod.modifyPursuit(obj);
        Integer currentVersion = obj.getVersion();
        Pursuit merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Pursuit' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PursuitIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", dod.getRandomPursuit());
        Pursuit obj = dod.getNewTransientPursuit(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pursuit' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Pursuit' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PursuitIntegrationTest.testRemove() {
        Pursuit obj = dod.getRandomPursuit();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pursuit' failed to provide an identifier", id);
        obj = Pursuit.findPursuit(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Pursuit' with identifier '" + id + "'", Pursuit.findPursuit(id));
    }
    
}
