// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.PursuitStatus;
import com.saic.tmr.domain.PursuitStatusDataOnDemand;
import com.saic.tmr.domain.PursuitStatusIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PursuitStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PursuitStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PursuitStatusIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PursuitStatusIntegrationTest: @Transactional;
    
    @Autowired
    private PursuitStatusDataOnDemand PursuitStatusIntegrationTest.dod;
    
    @Test
    public void PursuitStatusIntegrationTest.testCountPursuitStatuses() {
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", dod.getRandomPursuitStatus());
        long count = PursuitStatus.countPursuitStatuses();
        Assert.assertTrue("Counter for 'PursuitStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testFindPursuitStatus() {
        PursuitStatus obj = dod.getRandomPursuitStatus();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to provide an identifier", id);
        obj = PursuitStatus.findPursuitStatus(id);
        Assert.assertNotNull("Find method for 'PursuitStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PursuitStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testFindAllPursuitStatuses() {
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", dod.getRandomPursuitStatus());
        long count = PursuitStatus.countPursuitStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'PursuitStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PursuitStatus> result = PursuitStatus.findAllPursuitStatuses();
        Assert.assertNotNull("Find all method for 'PursuitStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PursuitStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testFindPursuitStatusEntries() {
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", dod.getRandomPursuitStatus());
        long count = PursuitStatus.countPursuitStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PursuitStatus> result = PursuitStatus.findPursuitStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PursuitStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PursuitStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testFlush() {
        PursuitStatus obj = dod.getRandomPursuitStatus();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to provide an identifier", id);
        obj = PursuitStatus.findPursuitStatus(id);
        Assert.assertNotNull("Find method for 'PursuitStatus' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPursuitStatus(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PursuitStatus' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testMergeUpdate() {
        PursuitStatus obj = dod.getRandomPursuitStatus();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to provide an identifier", id);
        obj = PursuitStatus.findPursuitStatus(id);
        boolean modified =  dod.modifyPursuitStatus(obj);
        Integer currentVersion = obj.getVersion();
        PursuitStatus merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PursuitStatus' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", dod.getRandomPursuitStatus());
        PursuitStatus obj = dod.getNewTransientPursuitStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PursuitStatus' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PursuitStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PursuitStatusIntegrationTest.testRemove() {
        PursuitStatus obj = dod.getRandomPursuitStatus();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitStatus' failed to provide an identifier", id);
        obj = PursuitStatus.findPursuitStatus(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PursuitStatus' with identifier '" + id + "'", PursuitStatus.findPursuitStatus(id));
    }
    
}
