// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.PursuitStatus;
import com.saic.tmr.domain.PursuitStatusDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PursuitStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PursuitStatusDataOnDemand: @Component;
    
    private Random PursuitStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<PursuitStatus> PursuitStatusDataOnDemand.data;
    
    public PursuitStatus PursuitStatusDataOnDemand.getNewTransientPursuitStatus(int index) {
        PursuitStatus obj = new PursuitStatus();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void PursuitStatusDataOnDemand.setCode(PursuitStatus obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void PursuitStatusDataOnDemand.setName(PursuitStatus obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public PursuitStatus PursuitStatusDataOnDemand.getSpecificPursuitStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PursuitStatus obj = data.get(index);
        Long id = obj.getId();
        return PursuitStatus.findPursuitStatus(id);
    }
    
    public PursuitStatus PursuitStatusDataOnDemand.getRandomPursuitStatus() {
        init();
        PursuitStatus obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PursuitStatus.findPursuitStatus(id);
    }
    
    public boolean PursuitStatusDataOnDemand.modifyPursuitStatus(PursuitStatus obj) {
        return false;
    }
    
    public void PursuitStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PursuitStatus.findPursuitStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PursuitStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PursuitStatus>();
        for (int i = 0; i < 10; i++) {
            PursuitStatus obj = getNewTransientPursuitStatus(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
