// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.PursuitRole;
import com.saic.tmr.domain.PursuitRoleDataOnDemand;
import com.saic.tmr.domain.PursuitRoleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PursuitRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PursuitRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PursuitRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PursuitRoleIntegrationTest: @Transactional;
    
    @Autowired
    private PursuitRoleDataOnDemand PursuitRoleIntegrationTest.dod;
    
    @Test
    public void PursuitRoleIntegrationTest.testCountPursuitRoles() {
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", dod.getRandomPursuitRole());
        long count = PursuitRole.countPursuitRoles();
        Assert.assertTrue("Counter for 'PursuitRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testFindPursuitRole() {
        PursuitRole obj = dod.getRandomPursuitRole();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to provide an identifier", id);
        obj = PursuitRole.findPursuitRole(id);
        Assert.assertNotNull("Find method for 'PursuitRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PursuitRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testFindAllPursuitRoles() {
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", dod.getRandomPursuitRole());
        long count = PursuitRole.countPursuitRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'PursuitRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PursuitRole> result = PursuitRole.findAllPursuitRoles();
        Assert.assertNotNull("Find all method for 'PursuitRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PursuitRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testFindPursuitRoleEntries() {
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", dod.getRandomPursuitRole());
        long count = PursuitRole.countPursuitRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PursuitRole> result = PursuitRole.findPursuitRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PursuitRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PursuitRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testFlush() {
        PursuitRole obj = dod.getRandomPursuitRole();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to provide an identifier", id);
        obj = PursuitRole.findPursuitRole(id);
        Assert.assertNotNull("Find method for 'PursuitRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPursuitRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PursuitRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testMergeUpdate() {
        PursuitRole obj = dod.getRandomPursuitRole();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to provide an identifier", id);
        obj = PursuitRole.findPursuitRole(id);
        boolean modified =  dod.modifyPursuitRole(obj);
        Integer currentVersion = obj.getVersion();
        PursuitRole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PursuitRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", dod.getRandomPursuitRole());
        PursuitRole obj = dod.getNewTransientPursuitRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PursuitRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PursuitRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PursuitRoleIntegrationTest.testRemove() {
        PursuitRole obj = dod.getRandomPursuitRole();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PursuitRole' failed to provide an identifier", id);
        obj = PursuitRole.findPursuitRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PursuitRole' with identifier '" + id + "'", PursuitRole.findPursuitRole(id));
    }
    
}
