// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.PursuitRole;
import com.saic.tmr.domain.PursuitRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PursuitRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PursuitRoleDataOnDemand: @Component;
    
    private Random PursuitRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<PursuitRole> PursuitRoleDataOnDemand.data;
    
    public PursuitRole PursuitRoleDataOnDemand.getNewTransientPursuitRole(int index) {
        PursuitRole obj = new PursuitRole();
        setName(obj, index);
        return obj;
    }
    
    public void PursuitRoleDataOnDemand.setName(PursuitRole obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public PursuitRole PursuitRoleDataOnDemand.getSpecificPursuitRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PursuitRole obj = data.get(index);
        Long id = obj.getId();
        return PursuitRole.findPursuitRole(id);
    }
    
    public PursuitRole PursuitRoleDataOnDemand.getRandomPursuitRole() {
        init();
        PursuitRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PursuitRole.findPursuitRole(id);
    }
    
    public boolean PursuitRoleDataOnDemand.modifyPursuitRole(PursuitRole obj) {
        return false;
    }
    
    public void PursuitRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PursuitRole.findPursuitRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PursuitRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PursuitRole>();
        for (int i = 0; i < 10; i++) {
            PursuitRole obj = getNewTransientPursuitRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
