// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.RFP;
import com.saic.tmr.domain.RFPDataOnDemand;
import com.saic.tmr.domain.RFPIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RFPIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RFPIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RFPIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RFPIntegrationTest: @Transactional;
    
    @Autowired
    private RFPDataOnDemand RFPIntegrationTest.dod;
    
    @Test
    public void RFPIntegrationTest.testCountRFPS() {
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", dod.getRandomRFP());
        long count = RFP.countRFPS();
        Assert.assertTrue("Counter for 'RFP' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RFPIntegrationTest.testFindRFP() {
        RFP obj = dod.getRandomRFP();
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RFP' failed to provide an identifier", id);
        obj = RFP.findRFP(id);
        Assert.assertNotNull("Find method for 'RFP' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RFP' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RFPIntegrationTest.testFindAllRFPS() {
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", dod.getRandomRFP());
        long count = RFP.countRFPS();
        Assert.assertTrue("Too expensive to perform a find all test for 'RFP', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RFP> result = RFP.findAllRFPS();
        Assert.assertNotNull("Find all method for 'RFP' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RFP' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RFPIntegrationTest.testFindRFPEntries() {
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", dod.getRandomRFP());
        long count = RFP.countRFPS();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RFP> result = RFP.findRFPEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RFP' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RFP' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RFPIntegrationTest.testFlush() {
        RFP obj = dod.getRandomRFP();
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RFP' failed to provide an identifier", id);
        obj = RFP.findRFP(id);
        Assert.assertNotNull("Find method for 'RFP' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRFP(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RFP' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RFPIntegrationTest.testMergeUpdate() {
        RFP obj = dod.getRandomRFP();
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RFP' failed to provide an identifier", id);
        obj = RFP.findRFP(id);
        boolean modified =  dod.modifyRFP(obj);
        Integer currentVersion = obj.getVersion();
        RFP merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RFP' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RFPIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", dod.getRandomRFP());
        RFP obj = dod.getNewTransientRFP(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RFP' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RFP' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RFP' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RFPIntegrationTest.testRemove() {
        RFP obj = dod.getRandomRFP();
        Assert.assertNotNull("Data on demand for 'RFP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RFP' failed to provide an identifier", id);
        obj = RFP.findRFP(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RFP' with identifier '" + id + "'", RFP.findRFP(id));
    }
    
}
