// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saic.tmr.domain;

import com.saic.tmr.domain.Target;
import com.saic.tmr.domain.TargetDataOnDemand;
import com.saic.tmr.domain.TargetIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TargetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TargetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TargetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TargetIntegrationTest: @Transactional;
    
    @Autowired
    private TargetDataOnDemand TargetIntegrationTest.dod;
    
    @Test
    public void TargetIntegrationTest.testCountTargets() {
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", dod.getRandomTarget());
        long count = Target.countTargets();
        Assert.assertTrue("Counter for 'Target' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TargetIntegrationTest.testFindTarget() {
        Target obj = dod.getRandomTarget();
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Target' failed to provide an identifier", id);
        obj = Target.findTarget(id);
        Assert.assertNotNull("Find method for 'Target' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Target' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TargetIntegrationTest.testFindAllTargets() {
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", dod.getRandomTarget());
        long count = Target.countTargets();
        Assert.assertTrue("Too expensive to perform a find all test for 'Target', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Target> result = Target.findAllTargets();
        Assert.assertNotNull("Find all method for 'Target' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Target' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TargetIntegrationTest.testFindTargetEntries() {
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", dod.getRandomTarget());
        long count = Target.countTargets();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Target> result = Target.findTargetEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Target' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Target' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TargetIntegrationTest.testFlush() {
        Target obj = dod.getRandomTarget();
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Target' failed to provide an identifier", id);
        obj = Target.findTarget(id);
        Assert.assertNotNull("Find method for 'Target' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTarget(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Target' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TargetIntegrationTest.testMergeUpdate() {
        Target obj = dod.getRandomTarget();
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Target' failed to provide an identifier", id);
        obj = Target.findTarget(id);
        boolean modified =  dod.modifyTarget(obj);
        Integer currentVersion = obj.getVersion();
        Target merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Target' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TargetIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", dod.getRandomTarget());
        Target obj = dod.getNewTransientTarget(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Target' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Target' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Target' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TargetIntegrationTest.testRemove() {
        Target obj = dod.getRandomTarget();
        Assert.assertNotNull("Data on demand for 'Target' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Target' failed to provide an identifier", id);
        obj = Target.findTarget(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Target' with identifier '" + id + "'", Target.findTarget(id));
    }
    
}
